apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
  {{ .Values.configmap.fileName }}: |-
    {{ .Files.Get (printf "files/%s.index.html" .Values.configmap.environment ) | nindent 4 }}