apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: {{ .Values.appName }}
  selector:
    app: {{ .Values.appName }}
  type: NodePort